### ISSUE TITLE
Consider tagging repo before breaking change

### ISSUE THREAD

**Issue by jvasak** [pelletier/go-buffruneio#2]
Trying to build go-toml v0.4.0 against master breaks (as noted in the commit messages), but creating a tag at df1e16fd would make is easier for dependency management tools.

**Comment by pelletier** [comment]
You're right. Just added the the v0.1.0 tag to df1e16fde7fc330a0ca68167c23bf7ed6ac31d6d. I'm also about to tag a new version of go-toml that includes the changes to make it compatible with the newer go-buffruneio.

**Comment by pelletier** [comment]
Just tagged go-toml v0.5.0: https://github.com/pelletier/go-toml/releases/tag/v0.5.0

Closing this, but please reopen and let me know if you still have any issue with this!
