### ISSUE TITLE
Add a LICENSE file for easier license detection

### ISSUE THREAD

**Issue by sagikazarmark** [pelletier/go-buffruneio#6]
Currently a number of license detection tools cannot properly find the license type (neither can github). Adding a `LICENSE` file makes it easier to pass compliance without ignoring your project and manually examining the license.

**Comment by henvic** [comment]
Same compliance issue here.

**Comment by pelletier** [comment]
Sorry about that oversight! Added (MIT) `LICENSE` file.

**Comment by sagikazarmark** [comment]
Awesome, thanks!
